#!/bin/bash
if [ $(id -u) != 0 ]; then
   echo "This script requires root permissions"
   sudo "$0" "$@"
   exit
fi

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
venv_dir="$HOME/.virtualenvs"
python_dir="$HOME/code/python"

printf "Installing python3, python3-venv and python3-pip"
apt-get -y install python3 python3-venv python3-pip

mkdir -p $python_dir
mkdir -p $venv_dir

printf "Adding pyv alias to ~/.bashrc\n"
printf '\n''alias pyv=". '$script_dir/pyv'"' >> ~/.bashrc
source ~/.bashrc

read -p "Create a new venv? " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
    printf "\n"
    read -p "venv name: " -r
    python3 -m venv "$venv_dir/$REPLY"
    mkdir -p $python_dir/$REPLY
    printf "Run pyv to activate your new venv"
fi