#!/bin/bash

# Either run the pysetup script, or add the following line to your ~/.bashrc manually.
# alias pyv=". PATHTOFILE/pyv"

venv_dir="$HOME/.virtualenvs"
python_dir="$HOME/code/python"

if [ $# -eq 1 ]
then
    python3 -m venv "$venv_dir/$1"
    source "$venv_dir/$1/bin/activate"
    mkdir -p $python_dir/$1
    cd $python_dir/$1
else
    printf "Please select a Python environment to activate:\n"
    select d in $venv_dir/*; do test -n "$d" && break; echo ">>> Invalid Selection"; done
    source $d"/bin/activate" 
    env_name="${d##*/}"
    mkdir -p $python_dir/$env_name
    cd $python_dir/$env_name
fi